# Generated by Django 5.1.7 on 2025-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
