# Generated by Django 5.1.7 on 2025-04-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
