# Generated by Django 5.1.7 on 2025-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_bloodrequest_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
