# Generated by Django 5.1.7 on 2025-04-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0003_bloodrequest_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='blood_bank.bloodrequest'),
        ),
    ]
