# Generated by Django 5.1.7 on 2025-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0004_donation_related_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='blood_group',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
