# Generated by Django 5.1.7 on 2025-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0005_remove_donation_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=10),
        ),
    ]
